main: dev.cibmc.spigot.superPlugin.App
name: superheroPlugin
version: 0.1
commands:
  giveglass:
    description: Gives Anne their eldrich glass blast
    usage: /<command>
  giveStaff:
    description: Gives Aya her slow staff
    usage: /<command>
  hilt:
    description: Give Maxis his conductive hilt
    usage: /<command>
  glassstack:
    description: Gives Anne a stack of glass blocks
    usage: /<command>
  addblock:
    description: Adds the block you're looking at to your inventory
    usage: /<command>